// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250419084736_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3363),
                            Name = "Meyve & Sebze",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3379),
                            Name = "Et & Tavuk",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3380),
                            Name = "Süt & Kahvaltılık",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3380),
                            Name = "Atıştırmalık",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3574),
                            Description = "Taze tarla domatesi",
                            ImagePath = "images/domates.jpg",
                            Name = "Domates",
                            Status = 1,
                            UnitPrice = 15.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3579),
                            Description = "Seradan taze salatalık",
                            ImagePath = "images/salatalik.jpg",
                            Name = "Salatalık",
                            Status = 1,
                            UnitPrice = 12.25m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3581),
                            Description = "Amasya elması",
                            ImagePath = "images/elma.jpg",
                            Name = "Elma",
                            Status = 1,
                            UnitPrice = 10.75m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3583),
                            Description = "Yerli patates",
                            ImagePath = "images/patates.jpg",
                            Name = "Patates",
                            Status = 1,
                            UnitPrice = 8.90m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3584),
                            Description = "Kuru soğan",
                            ImagePath = "images/sogan.jpg",
                            Name = "Soğan",
                            Status = 1,
                            UnitPrice = 7.30m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3585),
                            Description = "Yağsız dana kıyma",
                            ImagePath = "images/kiyma.jpg",
                            Name = "Dana Kıyma",
                            Status = 1,
                            UnitPrice = 210.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3587),
                            Description = "Taze tavuk fileto",
                            ImagePath = "images/tavuk.jpg",
                            Name = "Tavuk Göğsü",
                            Status = 1,
                            UnitPrice = 85.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3648),
                            Description = "Kayseri usulü fermente sucuk",
                            ImagePath = "images/sucuk.jpg",
                            Name = "Sucuk",
                            Status = 1,
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3650),
                            Description = "Kemikli kuzu pirzola",
                            ImagePath = "images/kuzupirzola.jpg",
                            Name = "Kuzu Pirzola",
                            Status = 1,
                            UnitPrice = 280.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3652),
                            Description = "Dilimli hindi füme",
                            ImagePath = "images/hindifume.jpg",
                            Name = "Hindi Füme",
                            Status = 1,
                            UnitPrice = 95.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3653),
                            Description = "Tam yağlı günlük süt",
                            ImagePath = "images/sut.jpg",
                            Name = "Süt",
                            Status = 1,
                            UnitPrice = 18.50m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3655),
                            Description = "Ezine tipi beyaz peynir",
                            ImagePath = "images/peynir.jpg",
                            Name = "Beyaz Peynir",
                            Status = 1,
                            UnitPrice = 98.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3656),
                            Description = "Kahvaltılık doğal tereyağı",
                            ImagePath = "images/tereyag.jpg",
                            Name = "Tereyağı",
                            Status = 1,
                            UnitPrice = 140.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3657),
                            Description = "Siyah sele zeytin",
                            ImagePath = "images/zeytin.jpg",
                            Name = "Zeytin",
                            Status = 1,
                            UnitPrice = 75.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3659),
                            Description = "Süzme çiçek balı",
                            ImagePath = "images/bal.jpg",
                            Name = "Bal",
                            Status = 1,
                            UnitPrice = 160.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3660),
                            Description = "Patates cipsi 150g",
                            ImagePath = "images/cips.jpg",
                            Name = "Cips",
                            Status = 1,
                            UnitPrice = 23.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3661),
                            Description = "Bitter çikolata 80g",
                            ImagePath = "images/cikolata.jpg",
                            Name = "Çikolata",
                            Status = 1,
                            UnitPrice = 18.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3663),
                            Description = "Kakaolu gofret",
                            ImagePath = "images/gofret.jpg",
                            Name = "Gofret",
                            Status = 1,
                            UnitPrice = 9.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3664),
                            Description = "Limon aromalı gazoz",
                            ImagePath = "images/gazoz.jpg",
                            Name = "Gazoz",
                            Status = 1,
                            UnitPrice = 7.50m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 4, 19, 11, 47, 35, 760, DateTimeKind.Local).AddTicks(3666),
                            Description = "Kremalı bisküvi",
                            ImagePath = "images/biskuvi.jpg",
                            Name = "Bisküvi",
                            Status = 1,
                            UnitPrice = 11.75m
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Product", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
